{% set name = "Ipopt" %}
{% set version = "3.14.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/coin-or/Ipopt/archive/releases/{{ version }}.tar.gz
    sha256: cc8c217991240db7eb14189eee0dff88f20a89bac11958b48625fa512fe8d104
    patches:
      - pkg-config-do-not-add-requires-private.patch

build:
  number: 10
  run_exports:
    - {{ pin_subpackage('ipopt', max_pin='x.x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - autotools_clang_conda  # [win]
    - make  # [not win]
    - wget  # [not win]
    - pkg-config
  host:
    - libblas
    - liblapack
    - mumps-seq
    - libspral  # [linux]
    - ampl-mp  # [not win]
    - ampl-asl  # [win]

test:
  files:
    - test
    - mytoy.nl

  requires:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config

about:
  home: https://projects.coin-or.org/Ipopt/
  license: EPL-1.0
  license_file: LICENSE
  summary: Software package for large-scale nonlinear optimization

extra:
  recipe-maintainers:
    - pstjohn
    - bluescarni
    - jschueller
    - moorepants
    - traversaro
