{% set name = "Ipopt" %}
{% set version = "3.13.0" %}
{% set sha256 = "dc392396be28c4a0d49bfab399320cb3f70db5b8f090028a883d826a47744ecf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.coin-or.org/download/source/{{ name }}/{{ name }}-{{ version }}.tgz
  sha256: {{ sha256 }}
  #patches:
    #- linux-configure.patch  # [linux]

build:
  skip: True  # [win]
  number: 0
  run_exports:
    - {{ pin_subpackage('ipopt', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - wget
  host:
    - libblas
    - liblapack
    - ampl-mp
    - metis
    - scotch
  run:
    - ampl-mp
    - metis
    - scotch

test:
  files:
    - test
    - mytoy.nl

  requires:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://projects.coin-or.org/Ipopt/
  license: EPL 1.0
  license_file: LICENSE
  summary: Software package for large-scale nonlinear optimization

extra:
  recipe-maintainers:
    - pstjohn
    - bluescarni
