{% set name = "Ipopt" %}
{% set version = "3.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/coin-or/Ipopt/archive/releases/{{ version }}.tar.gz
    sha256: 3ec6776b9a1ed8895f662bfc9939b067722770297be78ca4d6dc1cb42557da62
    patches:
      - linux-configure.patch  # [linux]
      - pkg-config-do-not-add-requires-private.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('ipopt', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]
    - make  # [not win]
    - wget  # [not win]
    - pkgconfig
  host:
    - libblas
    - liblapack
    - metis
    - mumps-seq
    - ampl-mp  # [not win]

test:
  files:
    - test
    - mytoy.nl

  requires:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkgconfig

about:
  home: https://projects.coin-or.org/Ipopt/
  license: EPL-1.0
  license_file: LICENSE
  summary: Software package for large-scale nonlinear optimization

extra:
  recipe-maintainers:
    - pstjohn
    - bluescarni
    - jschueller
    - moorepants
    - traversaro
