{% set name = "Ipopt" %}
{% set version = "3.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/coin-or/Ipopt/archive/releases/{{ version }}.tar.gz
    sha256: 9bed72a5456ef37f1b95746c932986e6664eb70b983d4fab61cf8aa811facdf1
    patches:
      - linux-configure.patch  # [linux]
      - pkg-config-do-not-add-requires-private.patch

build:
  number: 1
  skip: true  # [win]
  string: {{ mkl_support }}
  script_env:
    - MKL_SUPPORT={{ mkl_support }}
  run_exports:
    - {{ pin_subpackage('ipopt', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]
    - wget  # [not win]
    - pkgconfig
  host:
    - libblas           # [mkl_support == 'nomkl']
    - liblapack         # [mkl_support == 'nomkl']
    - liblapack * *mkl  # [mkl_support == 'mkl']
    - libblas * *mkl    # [mkl_support == 'mkl']
    - metis
    - mumps-seq
    - ampl-mp           # [not win]
  run:
    - mkl               # [mkl_support == 'mkl']

test:
  files:
    - test
    - mytoy.nl

  requires:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkgconfig

about:
  home: https://projects.coin-or.org/Ipopt/
  license: EPL-1.0
  license_file: LICENSE
  summary: Software package for large-scale nonlinear optimization

extra:
  recipe-maintainers:
    - pstjohn
    - bluescarni
    - jschueller
    - moorepants
    - traversaro
