{% set name = "Ipopt" %}
{% set version = "3.12.7" %}
{% set sha256 = "e53d008fb2713cc6ee80035c4f312b7efaa5d5162a944298f92481b4aafe68b2" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.coin-or.org/download/pkgsource/{{ name }}/{{ name }}-{{ version }}.tgz
  sha256: {{ sha256 }}
  patches:
    - ipopt.patch

build:
  skip: True  # [win]
  number: 2
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain
    - ampl-mp
    - mumps
    - metis 5.1.*
    - scotch
    - gcc                           # [osx]
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*

  run:
    - ampl-mp
    - mumps
    - metis 5.1.*
    - scotch
    - libgfortran
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*

test:
  files:
    - test
    - mytoy.nl

  requires:
    - toolchain

about:
  home: https://projects.coin-or.org/Ipopt/
  license: EPL 1.0
  license_file: LICENSE
  summary: Software package for large-scale nonlinear optimization

extra:
  recipe-maintainers:
    - pstjohn
    - bluescarni
