{% set name = "Ipopt" %}
{% set version = "3.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: Ipopt
    url: https://github.com/coin-or/Ipopt/archive/releases/{{ version }}.tar.gz
    sha256: 86354b36c691e6cd6b8049218519923ab0ce8a6f0a432c2c0de605191f2d4a1c
    patches:
      - linux-configure.patch  # [linux]

  - folder: ASL
    url: https://github.com/coin-or-tools/ThirdParty-ASL/archive/releases/1.4.3.tar.gz
    sha256: 0a4cfa7c6c5df72d8e1c4c3ce74633421f807115a679e85cb5569c41df9a9aaf

build:
  skip: true  # [win]
  number: 1
  run_exports:
    - {{ pin_subpackage('ipopt', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - wget
    - pkgconfig
  host:
    - libblas
    - liblapack
    - metis
    - mumps-seq
  run:

test:
  files:
    - test
    - mytoy.nl

  requires:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://projects.coin-or.org/Ipopt/
  license: EPL-1.0
  license_file: Ipopt/LICENSE
  summary: Software package for large-scale nonlinear optimization

extra:
  recipe-maintainers:
    - pstjohn
    - bluescarni
    - jschueller
