{% set name = "Ipopt" %}
{% set version = "3.12.8" %}
{% set sha256 = "54938be9b7398869a7d3974e545117884001847e23939ba0a2c71fa7a898210f" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.coin-or.org/download/pkgsource/{{ name }}/{{ name }}-{{ version }}.tgz
  sha256: {{ sha256 }}
  patches:
    - ipopt.patch

build:
  number: 3
  skip: True  # [win]
  number: 0
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain
    - ampl-mp
    - mumps
    - metis 5.1.*
    - scotch
    - gcc                           # [osx]
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*

  run:
    - ampl-mp
    - mumps
    - metis 5.1.*
    - scotch
    - libgfortran
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*

test:
  files:
    - test
    - mytoy.nl

  requires:
    - toolchain

about:
  home: https://projects.coin-or.org/Ipopt/
  license: EPL 1.0
  license_file: LICENSE
  summary: Software package for large-scale nonlinear optimization

extra:
  recipe-maintainers:
    - pstjohn
    - bluescarni
