{% set name = "Ipopt" %}
{% set version = "3.14.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/coin-or/Ipopt/archive/releases/{{ version }}.tar.gz
    sha256: 17ab8e9a6059ab11172c184e5947e7a7dda9fed0764764779c27e5b8e46f3d75
    patches:
      - pkg-config-do-not-add-requires-private.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('ipopt', max_pin='x.x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    # Do not depend on a fortran compiler on Windows,
    # see https://github.com/conda-forge/ipopt-feedstock/pull/125#issuecomment-2543175086
    # for more details
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - autotools_clang_conda  # [win]
    - make  # [not win]
    - wget  # [not win]
    - pkg-config
  host:
    - libblas
    - liblapack
    - mumps-seq
    - libspral  # [linux]
    - ampl-asl

test:
  files:
    - test
    - mytoy.nl

  requires:
    # Do not depend on a fortran compiler on Windows,
    # see https://github.com/conda-forge/ipopt-feedstock/pull/125#issuecomment-2543175086
    # for more details
    - {{ compiler('fortran') }}   # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config

about:
  home: https://projects.coin-or.org/Ipopt/
  license: EPL-1.0
  license_file: LICENSE
  summary: Software package for large-scale nonlinear optimization

extra:
  recipe-maintainers:
    - pstjohn
    - bluescarni
    - jschueller
    - moorepants
    - traversaro
