{% set name = "Ipopt" %}
{% set version = "3.12.13" %}
{% set sha256 = "aac9bb4d8a257fdfacc54ff3f1cbfdf6e2d61fb0cf395749e3b0c0664d3e7e96" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: http://www.coin-or.org/download/source/{{ name }}/{{ name }}-{{ version }}.tgz
    fn: {{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 1000

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]
    - m2w64-toolchain  # [win]
    - mumps-seq
    - libblas
    - liblapack
  host:
    - mumps-seq
    - libblas
    - liblapack
    - ampl-mp  # [not win]
    - metis  # [not win]
    - scotch  # [not win]
  run:
    - ampl-mp  # [not win]
    - metis  # [not win]
    - scotch  # [not win]
    - m2w64-gcc-libs-core  # [win]
    - m2w64-gcc-libs  # [win]
    - mumps-seq  # [win]
    - libblas  # [win]
    - liblapack  # [win]

test:
  files:
    - test
    - mytoy.nl

  requires:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://projects.coin-or.org/Ipopt/
  license: EPL 1.0
  license_file: LICENSE
  summary: Software package for large-scale nonlinear optimization

extra:
  recipe-maintainers:
    - pstjohn
    - bluescarni
