{% set name = "Ipopt" %}
{% set version = "3.12.13" %}
{% set sha256 = "aac9bb4d8a257fdfacc54ff3f1cbfdf6e2d61fb0cf395749e3b0c0664d3e7e96" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.coin-or.org/download/source/{{ name }}/{{ name }}-{{ version }}.tgz
  sha256: {{ sha256 }}
  patches:
    - linux-configure.patch  # [linux]

build:
  skip: True  # [win]
  number: 1
  run_exports:
    - {{ pin_subpackage('ipopt', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - liblapack
    - ampl-mp
    - mumps-seq
    - metis
    - scotch
  run:
    - ampl-mp
    - mumps-seq
    - metis
    - scotch

test:
  files:
    - test
    - mytoy.nl

  requires:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://projects.coin-or.org/Ipopt/
  license: EPL 1.0
  license_file: LICENSE
  summary: Software package for large-scale nonlinear optimization

extra:
  recipe-maintainers:
    - pstjohn
    - bluescarni
