# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxfortran_compilergfortran
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxfortran_compilertoolchain_fort

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "YtkMsfAR3W/Ju7iM9wVLhUAWJ+Dmofl2gvro7Om1dRnQRyK8i05di/0iKVNPfIXYABkacjiQM7a+SLd9wYkntYXQp/XEkD64KpqNGJurK/jl6RFtkfTKfBPcmoj1vbU0JyOlR11ThNzqrLQr6VOTxwQL0YlDO1TJovFTO2Y7nrPjGJePGVCKcNxH1d4ASthB/TaGbG47+Wyw3r2tbzz5sP3cCQunVVB9vt6+2XqbSLi6lxRIZoNFpcRLsW5d65sRA3wgYyuDk9rjeFdPqOu0YHBkHFm8CvjV9k/1+8sNExERKoA8mzHK3TwB5cL6ddYivmjBTFHnr6YlFukeGTtKIWXKmxqGag7TlhWh1fkvhcRZEDzBI0fA62R0zQD140FC+nITwmhuy3386FDHj1rrM3Rl5LIq1I+k93K4ltGLcJyMB1d55vp+KoXWB/fNIbrBbz2AlsCN0/EflAttoDimJTBn63z21ynz2bih1JCgz6CNstkNGzf3aBS4enG/IRFULK89IISc5Tf2udcIEMaePYUgs7HI0VhnWvqJrbuxkhEWa4bXgOXUTjS+teDdu6OqOYK4CjUpyVgz9DMwQfA6Mdy2TIqvYDIA16Xu/Ls8InjT8SLcuiLXQ5H/bnEzrT31yenlCuKZRUiy31NRzPZpNdHKfNpuKYuW4ywqFj3HIlE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
