appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: YtkMsfAR3W/Ju7iM9wVLhUAWJ+Dmofl2gvro7Om1dRnQRyK8i05di/0iKVNPfIXYABkacjiQM7a+SLd9wYkntYXQp/XEkD64KpqNGJurK/jl6RFtkfTKfBPcmoj1vbU0JyOlR11ThNzqrLQr6VOTxwQL0YlDO1TJovFTO2Y7nrPjGJePGVCKcNxH1d4ASthB/TaGbG47+Wyw3r2tbzz5sP3cCQunVVB9vt6+2XqbSLi6lxRIZoNFpcRLsW5d65sRA3wgYyuDk9rjeFdPqOu0YHBkHFm8CvjV9k/1+8sNExERKoA8mzHK3TwB5cL6ddYivmjBTFHnr6YlFukeGTtKIWXKmxqGag7TlhWh1fkvhcRZEDzBI0fA62R0zQD140FC+nITwmhuy3386FDHj1rrM3Rl5LIq1I+k93K4ltGLcJyMB1d55vp+KoXWB/fNIbrBbz2AlsCN0/EflAttoDimJTBn63z21ynz2bih1JCgz6CNstkNGzf3aBS4enG/IRFULK89IISc5Tf2udcIEMaePYUgs7HI0VhnWvqJrbuxkhEWa4bXgOXUTjS+teDdu6OqOYK4CjUpyVgz9DMwQfA6Mdy2TIqvYDIA16Xu/Ls8InjT8SLcuiLXQ5H/bnEzrT31yenlCuKZRUiy31NRzPZpNdHKfNpuKYuW4ywqFj3HIlE=}
